--------------------------------------------------------
--  File created - Wednesday-May-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBLCATEGORIES
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLCATEGORIES" 
   (	"CATEGORYID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATECGORYNAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"CREATEDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLCUSTOMER
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLCUSTOMER" 
   (	"CUSTOMERID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CUSTOMERNAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MEMBERID" VARCHAR2(50 BYTE), 
	"CUSDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLEMPLOYEES
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLEMPLOYEES" 
   (	"EMPLOYEEID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEENAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLITEM
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLITEM" 
   (	"ITEMID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICEIN" NUMBER, 
	"PRICEOUT" NUMBER, 
	"CATEGORYID" NUMBER, 
	"ITEMQTY" NUMBER, 
	"ITEMDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLMEMBERS
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLMEMBERS" 
   (	"MEMBERID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MEMBERNAME" VARCHAR2(50 BYTE), 
	"DISCOUNT" FLOAT(126), 
	"CREATEDDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLORDER
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLORDER" 
   (	"ORDERID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEEID" NUMBER, 
	"CUSTOMERID" NUMBER, 
	"CREATEDATE" DATE, 
	"CREATEBY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLORDERDETAILS
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLORDERDETAILS" 
   (	"ORDERID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ITEMID" NUMBER, 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER, 
	"PRICE" VARCHAR2(50 BYTE), 
	"ORDERDETAILDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBLUSER
--------------------------------------------------------

  CREATE TABLE "COFFEESHOP"."TBLUSER" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(50 BYTE), 
	"PHONENUMBER" NUMBER, 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into COFFEESHOP.TBLCATEGORIES
SET DEFINE OFF;
Insert into COFFEESHOP.TBLCATEGORIES (CATEGORYID,CATECGORYNAME,DESCRIPTION,CREATEDATE) values (21,'s','z',to_date('06-MAY-23','DD-MON-RR'));
Insert into COFFEESHOP.TBLCATEGORIES (CATEGORYID,CATECGORYNAME,DESCRIPTION,CREATEDATE) values (2,'yat','hi',to_date('03-MAY-23','DD-MON-RR'));
REM INSERTING into COFFEESHOP.TBLCUSTOMER
SET DEFINE OFF;
Insert into COFFEESHOP.TBLCUSTOMER (CUSTOMERID,CUSTOMERNAME,PHONE,EMAIL,MEMBERID,CUSDATE) values (67,'WQ','832437872432','QQ','21',to_date('09-MAY-23','DD-MON-RR'));
REM INSERTING into COFFEESHOP.TBLEMPLOYEES
SET DEFINE OFF;
Insert into COFFEESHOP.TBLEMPLOYEES (EMPLOYEEID,EMPLOYEENAME,EMAIL,PHONE,ADDRESS) values (23,'222','ww','1342','qq');
Insert into COFFEESHOP.TBLEMPLOYEES (EMPLOYEEID,EMPLOYEENAME,EMAIL,PHONE,ADDRESS) values (1,'chengsam','admiN@gmail.com','1231232223','sr');
REM INSERTING into COFFEESHOP.TBLITEM
SET DEFINE OFF;
REM INSERTING into COFFEESHOP.TBLMEMBERS
SET DEFINE OFF;
Insert into COFFEESHOP.TBLMEMBERS (MEMBERID,MEMBERNAME,DISCOUNT,CREATEDDATE) values (21,'34',12,to_date('18-MAY-23','DD-MON-RR'));
Insert into COFFEESHOP.TBLMEMBERS (MEMBERID,MEMBERNAME,DISCOUNT,CREATEDDATE) values (23,'22',11,to_date('18-MAY-23','DD-MON-RR'));
REM INSERTING into COFFEESHOP.TBLORDER
SET DEFINE OFF;
REM INSERTING into COFFEESHOP.TBLORDERDETAILS
SET DEFINE OFF;
REM INSERTING into COFFEESHOP.TBLUSER
SET DEFINE OFF;
Insert into COFFEESHOP.TBLUSER (ID,NAME,PHONENUMBER,ADDRESS,PASSWORD) values (21,'admin',345873465,'sr','123');
--------------------------------------------------------
--  DDL for Index TBLMEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEESHOP"."TBLMEMBER_PK" ON "COFFEESHOP"."TBLMEMBERS" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBLEMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEESHOP"."TBLEMPLOYEES_PK" ON "COFFEESHOP"."TBLEMPLOYEES" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure ADDCATEGORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDCATEGORY" 
(
vname tblcategories.catecgoryname%type,
vdescription tblcategories.description%TYPE,
vcreatedate tblcategories.createdate%type

)
is
begin
insert into tblcategories(catecgoryname,description,createdate)
values (vname,vdescription,vcreatedate);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDCUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDCUSTOMER" 
(
vname tblcustomer.customername%type,
vphone tblcustomer.phone%type,
vemail tblcustomer.email%TYPE,
vmemberid tblcustomer.memberid%TYPE,
vdate tblcustomer.cusdate%TYPE
)
is
begin
insert into tblcustomer(customername,phone,email,memberid,cusdate)
values (vname,vphone,vemail,vmemberid,vdate);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDEMPLOYEES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDEMPLOYEES" 
(
vname tblemployees.employeename%type,
vemail tblemployees.email%TYPE,
vphone tblemployees.phone%type,
vaddress tblemployees.address%TYPE

)
is
begin
insert into tblemployees(employeename,email,phone,address)
values (vname,vemail,vphone,vaddress);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDITEM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDITEM" 
(
vname tblitem.name%type,
vpricein tblitem.pricein%type,
vpriceout tblitem.priceout%TYPE,
vcategoryid tblitem.categoryid%TYPE,
vitemqty tblitem.itemqty%TYPE,
vitemdate tblitem.itemdate%TYPE,
vcreatedby tblitem.createdby%TYPE
)
is
begin
insert into tblitem(name,pricein,priceout,categoryid,itemqty,itemdate,createdby)
values (vname,vpricein,vpriceout,vcategoryid,vitemqty,vitemdate,vcreatedby);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDMEMBERS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDMEMBERS" 
(
vmembername tblmembers.membername%type,
vdiscount tblmembers.discount%type,
vcreateddate tblmembers.createddate%TYPE
)
is
begin
insert into tblmembers(membername,discount,createddate)
values (vmembername,vdiscount,vcreateddate);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDORDER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDORDER" 
(
vemployeeid tblorder.employeeid%type,
vcustomerid tblorder.customerid%type,
vcreatedate tblorder.createdate%TYPE,
vcreateby tblorder.createby%TYPE
)
is
begin
insert into tblorder(employeeid,customerid,createdate,createby)
values (vemployeeid,vcustomerid,vcreatedate,vcreateby);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDORDERDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDORDERDETAILS" 
(
vdescription tblorderdetails.description%type,
vquantity tblorderdetails.quantity%TYPE,
vprice tblorderdetails.price%TYPE,
vorderdetaildate tblorderdetails.orderdetaildate%type,
vcreatedby tblorderdetails.createdby%TYPE
)
is
begin
insert into tblorderdetails(description,quantity,price,orderdetaildate,createdby)
values (vdescription,vquantity,vprice,vorderdetaildate,vcreatedby);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."ADDUSER" 
(
vname tbluser.name%type,
vphone tbluser.phonenumber%type,
vaddress tbluser.address%type
)
is
begin
insert into tbluser(name,phonenumber,address)
values (vname,vphone,vaddress);
end;

/
--------------------------------------------------------
--  DDL for Procedure DELETECATEGORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETECATEGORY" 
(
vid tblcategories.categoryid%type

)
is
begin
delete from tblcategories where categoryid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETECUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETECUSTOMER" 
(
vid tblcustomer.customerid%type

)
is
begin
delete from tblcustomer where customerid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETEEMPLOYEE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETEEMPLOYEE" 
(
vid tblemployees.employeeid%type

)
is
begin
delete from tblemployees where employeeid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETEITEM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETEITEM" 
(
vid tblitem.itemid%type

)
is
begin
delete from tblitem where itemid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETEMEMBER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETEMEMBER" 
(
vid tblmembers.memberid%type

)
is
begin
delete from tblmembers where memberid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETEORDER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETEORDER" 
(
vid tblorder.orderid%type

)
is
begin
delete from tblorder where orderid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETEORDERDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETEORDERDETAILS" 
(
vid tblorderdetails.orderid%type

)
is
begin
delete from tblorderdetails where orderid=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure DELETEUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."DELETEUSER" 
(
vid tbluser.id%type

)
is
begin
delete from tbluser where id=vid;

end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWCATEGORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWCATEGORY" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblcategories;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWCUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWCUSTOMER" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblcustomer;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWEMPLOYEE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWEMPLOYEE" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblemployees;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWITEM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWITEM" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblitem;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWMEMBER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWMEMBER" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblmembers;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWORDER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWORDER" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblorder;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWORDERDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWORDERDETAILS" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tblorderdetails;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure SHOWUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."SHOWUSER" 
is
    c1 SYS_REFCURSOR;
BEGIN
    open c1 FOR
    select * FROM tbluser;
    dbms_sql.return_result(c1);
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATECATEGORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATECATEGORY" 
(
vid tblcategories.categoryid%TYPE,
vcategoryname tblcategories.catecgoryname%TYPE,
vdescription tblcategories.description%type,
vcreatedate tblcategories.createdate%TYPE

)
is
begin
update tblcategories set catecgoryname=vcategoryname,description=vdescription,createdate=vcreatedate where categoryid=vid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATECUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATECUSTOMER" 
(
vid tblcustomer.customerid%TYPE,
vname tblcustomer.customername%type,
vemail tblcustomer.email%TYPE,
vphone tblcustomer.phone%type,
vaddress tblcustomer.address%TYPE

)
is
begin
update tblcustomer set customername=vname,email=vemail,phone=vphone,address=vaddress where customerid=vid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEEMPLOYEE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATEEMPLOYEE" 
(
vid tblemployees.employeeid%TYPE,
vname tblemployees.employeename%type,
vemail tblemployees.email%TYPE,
vphone tblemployees.phone%type,
vaddress tblemployees.address%TYPE

)
is
begin
update tblemployees set employeename=vname,email=vemail,phone=vphone,address=vaddress where employeeid=vid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEITEM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATEITEM" 
(
vid tblitem.itemid%TYPE,
vname tblitem.name%type,
vpricein tblitem.pricein%TYPE,
vpriceout tblitem.priceout%type,
vcategoryid tblitem.categoryid%TYPE,
vitemqty tblitem.itemqty%TYPE,
vitemdate tblitem.itemdate%TYPE,
vcreatedby tblitem.createdby%TYPE
)
is
begin
update tblitem set name=vname,pricein=vpricein,priceout=vpriceout,categoryid=vcategoryid,itemqty=vitemqty,itemdate=vitemdate,createdby=vcreatedby where itemid=vid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEMEMBERS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATEMEMBERS" 
(
vmemberid tblmembers.memberid%type,
vmembername tblmembers.membername%type,
vdiscount tblmembers.discount%type,
vcreateddate tblmembers.createddate%TYPE
)
is
begin
update tblmembers set membername=vmembername,discount=vdiscount,createddate=vcreateddate where memberid=vmemberid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEORDER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATEORDER" 
(
vid tblorder.orderid%TYPE,
vemployeeid tblorder.employeeid%TYPE,
vcustomerid tblorder.customerid%type,
vcreatedate tblorder.createdate%TYPE,
vcreateby tblorder.createby%type
)
is
begin
update tblorder set employeeid=vemployeeid,customerid=vcustomerid,createdate=vcreatedate,createby=vcreateby where orderid=vid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEORDERDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATEORDERDETAILS" 
(
vid tblorderdetails.orderid%TYPE,
vdescription tblorderdetails.description%TYPE,
vquantity tblorderdetails.quantity%type,
vprice tblorderdetails.price%TYPE,
vorderdetaildate tblorderdetails.orderdetaildate%TYPE,
vcreatedby tblorderdetails.createdby%TYPE

)
is
begin
update tblorderdetails set description=vdescription,quantity=vquantity,price=vprice,orderdetaildate=vorderdetaildate,createdby=vcreatedby where orderid=vid ;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEESHOP"."UPDATEUSER" 
(
vid tbluser.id%type,
vname tbluser.name%type,
vphone tbluser.phonenumber%type,
vaddress tbluser.address%type
)
is
begin
update tbluser set name=vname,phonenumber=vphone,address=vaddress where id=vid ;

end;

/
--------------------------------------------------------
--  Constraints for Table TBLCATEGORIES
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLCATEGORIES" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLCATEGORIES" MODIFY ("CREATEDATE" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLCATEGORIES" ADD PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLEMPLOYEES
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLEMPLOYEES" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLEMPLOYEES" MODIFY ("EMPLOYEENAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLEMPLOYEES" ADD CONSTRAINT "TBLEMPLOYEES_PK" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLMEMBERS
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLMEMBERS" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLMEMBERS" MODIFY ("MEMBERNAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLMEMBERS" ADD CONSTRAINT "TBLMEMBER_PK" PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLORDERDETAILS
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLORDERDETAILS" MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLORDERDETAILS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLCUSTOMER
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLCUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLCUSTOMER" ADD PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLUSER
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLUSER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLUSER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLUSER" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLUSER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLUSER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLORDER
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLORDER" MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLORDER" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLORDER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLORDER" MODIFY ("CREATEDATE" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLORDER" MODIFY ("CREATEBY" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLORDER" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLITEM
--------------------------------------------------------

  ALTER TABLE "COFFEESHOP"."TBLITEM" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "COFFEESHOP"."TBLITEM" ADD PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
